### ISSUE TITLE
The installation directory specified by the user is not used

### ISSUE THREAD

**Issue by leeebo** [georgik/esp-helm#6]
* Choose to install in `D:\espressif`
* But finally installed to `C:\espressif`, my `D:\espressif` is empty after the install

![image](https://github.com/georgik/esp-helm/assets/16922815/3b97dd64-2d1a-4b09-8a2a-81f1a35fa63c)

**Comment by georgik** [comment]
@leeebo Thank you for spotting the problem with setting the value of the directory.

The correction is in place and new build is available: https://github.com/georgik/esp-helm/releases/tag/app-v0.0.4
